### PR TITLE
IWA NTLM Authenticator code transfer

### PR DESCRIPTION
**Pull request by mefarazath**

### CODE REVIEW

**Comment by mefarazath** [comment]
The code was migrated from the old [repo](https://github.com/wso2-extensions/identity-local-auth-iwa-kerberos/tree/v5.1.2) along with the history of commits.

The changes relevant to making this authenticator a connector are the last four commits

**Comment by mefarazath** [comment]
@pulasthi7 shall we merge this PR and add the IWA NTLM Authenticator to the store?

**Comment by pulasthi7** [comment]
@mefarazath Can you squash the last 4 commits you mentioned, so that they can be easily reviewed?

**Comment by mefarazath** [comment]
@pulasthi7 done!

**Comment by mefarazath** [comment]
Closing this PR as the updated one is available with https://github.com/wso2-extensions/identity-local-auth-iwa-ntlm/pull/4

**Pull request closed without merging**
